version: "3.8"
services:
  where-is-my-money-api:
    image: augustomarques/where-is-my-money-api
    container_name: where-is-my-money-api
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SERVER_PORT: 8080
      DB_URL: postgres
      DB_PORT: 5432
      DB_DATABASE: where-is-my-money
      DB_USERNAME: user-where-is-my-money
      DB_PASSWORD: password-where-is-my-money
    ports:
      - "1212:8080"
    networks:
      - where-is-my-money-network
  
  where-is-my-money-frontend:
    image: augustomarques/where-is-my-money-frontend
    container_name: where-is-my-money-frontend
    restart: unless-stopped
    ports:
      - "8099:80"
    networks:
      - where-is-my-money-network

networks:
  where-is-my-money-network:
    name: development
    external: true
