global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "biluca-api"
    metrics_path: /actuator/prometheus
    static_configs:
    - targets:
      - "biluca-api:8080"
      # - targets: ['host.docker.internal:8080']
