version: '3' 

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: RABBITMQ_SECRET_PHRASE
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
