global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: "biluca-api"
    metrics_path: /actuator/prometheus
    static_configs:
    - targets:
      - "biluca-api:8080"
  - job_name: "where-is-my-money-api"
    metrics_path: /actuator/prometheus
    static_configs:
    - targets:
      - "where-is-my-money-api:8080"
