version: "3.8"
services:
  api-login:
    image: augustomarques/biluca
    container_name: app-biluca-api
    # build: .
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: biluca
      DB_USER: user-biluca
      DB_PASSWORD: password-biluca
    ports:
      - "8080:8080"
    networks:
      - biluca-network

networks:
  biluca-network:
    name: development
    external: true