version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: "%"
    command: --lower_case_table_names=1
