version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - $PWD/database/PostgreSQL:/var/lib/postgresql/data 
